-- Unidojo MVP database schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  age integer,
  income numeric default 0,
  rent numeric default 0,
  weekly_spend numeric default 0,
  goal text,
  confidence integer default 3,
  xp integer default 0,
  streak integer default 0,
  decisions integer default 0,
  saved numeric default 0,
  lesson integer default 0,
  onboarding_complete boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.decisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric not null,
  outcome text not null check (outcome in ('bought','skipped')),
  created_at timestamptz default now()
);

create table if not exists public.paper_portfolios (
  user_id uuid primary key references auth.users(id) on delete cascade,
  cash numeric not null default 10000,
  holdings jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.decisions enable row level security;
alter table public.paper_portfolios enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "decisions own rows" on public.decisions;
create policy "decisions own rows" on public.decisions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "portfolio own row" on public.paper_portfolios;
create policy "portfolio own row" on public.paper_portfolios for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name) values (new.id, coalesce(new.raw_user_meta_data->>'name',''))
  on conflict (id) do nothing;
  insert into public.paper_portfolios (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
